apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yrtre7geq-java-quarkus
  janus-idp.io/tekton: yrtre7geq-java-quarkus
  backstage.io/kubernetes-id: yrtre7geq-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yrtre7geq-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
